### PR TITLE
Allow cookie-0.5

### PR DESCRIPTION
**Pull request by spencerjanssen**

### CODE REVIEW

**Comment by ysangkok** [comment]
@swamp-agr This would be nice to merge, since it would help unblock Stackage from upgrading cookie.

**Comment by juhp** [comment]
Ping (for stackage)

I suppose a Hackage revision could be done also.
I could help with that if needed.

**Comment by ysangkok** [comment]
@juhp I wouldn't object, **but** it would be even better if all the bumps in #255 were done. I was thinking to wait a few weeks because the PR is too new, so trustees might tell me to wait.

**Comment by ysangkok** [comment]
this can be closed, it was fixed with v2.8.9 and https://github.com/GetShopTV/swagger2/pull/255

**Comment by swamp-agr** [comment]
Closed in favour of #255

**Pull request closed without merging**
