### PR TITLE
Allow omitting type and infer it when validating

### LINKED ISSUE #138: Make schema type optional
See https://github.com/GetShopTV/swagger2/issues/131#issuecomment-339069562.

### PR DESCRIPTION
**Pull request by fizruk**
This fixes #138.

For type inference I use the same algorithm as in https://github.com/json-schema-faker/json-schema-faker#inferred-types:
- if type is present everything works like before;
- if type is absent, it is inferred based on properties used in schema;
- if no type can be inferred — validation fails;
- if more than one type is inferred — validation fails.

Note that this is a breaking change:
- users have to change `type_ .~ ...` to `type ?~ ...`
- `mempty :: Schema` is now with implicit type (was `SwaggerString` before).

This PR supersedes #163 (that one used a different inference mechanism).

### CODE REVIEW

**Comment by kahlil29** [comment]
Hey @fizruk @phadej  
Just got hit by this issue (#138) while testing the parsing of `Swagger` specs. (I've written a tool that parses `Swagger` specs and generates some Haskell code) 

Any idea if there's something blocking the merging of this PR? 
Would really appreciate some insight into this 😄

**Comment by fizruk** [comment]
@phadej I have rebased, so it should probably be fine for merge now 😊

**Comment by kahlil29** [comment]
@phadej A gentle reminder about this, whenever you get the time 😸

**Comment by kahlil29** [comment]
@phadej 
Do let us know if there's anything pending in order for this to be merged 😄

**Comment by kahlil29** [comment]
@phadej ping! 😄 
 Hope I'm not pestering you too much 😛

**Comment by phadej** [comment]
Merged. But I don't know when I'll have proper time to make the release (it's including major bump, so one would like to use that opportunity to merge other breaking stuff)

**Comment by phadej** [comment]
Ok. I accidentally removed the inferring when rebasing #163, and none of the tests failed. I.e. there are no tests.

Reverting this until there are.

**Comment by kahlil29** [comment]
@phadej Cool, thanks a lot. 
I'm currently using it as an extra-dep and pointing to the latest commit on this branch. Guess I'll continue doing that till this is released. 

Do tests need to be written? I could probably try and help with that, if necessary. 
@fizruk

**Comment by phadej** [comment]
@kahlil29 `validateToJSON` is tested only with doctests in `Schema.Validation`; given how much code is in `Internal/Schema/Validation.hs`.

Specifically I don't see any test where `type` is omitted and schema is inferred.

**Pull request merged**
