### PR TITLE
Fix ghc 7.8 build

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
Hmm, seems that GHC 7.8 support would require some changes. Do you have any intentions to support it?

**Comment by fizruk** [comment]
@phadej I think I should. BTW, should Travis use cabal-install or stack for builds?

**Comment by phadej** [comment]
IMHO i'd rather use `cabal-install`. It's easy to support particular Stackage snapshots by getting `cabal.config`s for them.

**Comment by fizruk** [comment]
@phadej ok then, thanks for the fixes!

**Pull request merged**
