### PR TITLE
Support GHC 9.2

### LINKED ISSUE #227: GHC 9.2 support
TODO:

- [ ] `optics-th-0.4` depends on `template-haskell`.
- [ ] `lens-5.0.1` depends on `template-haskell`.
- [ ] `insert-ordered-containers-0.2.5` depends on `base`.
- [ ] `http-media-0.8.0.0` depends on `base`.
- [ ] `generics-sop-0.5.1.1` depends on `base` `ghc-prim`, `temlate-haskell`.
- [ ] `sop-core-0.5.0.1` depends on `base`.
- [ ] `aeson-2.0.1.0` depends on `ghc-prim`, `template-haskell`.
- [ ] `cabal-doctest-1.0.8` depends on `base`, `Cabal` (subject of deprecation?).

### PR DESCRIPTION
**Pull request by brandon-leapyear**
Resolves #227, uses the fix in the comments

### CODE REVIEW

**Comment by ysangkok** [comment]
Does the test suite pass for you with this patch applied? Because it didn't for me (as you can see in the bottom of that comment you refer to).

**Comment by brandon-leapyear** [comment]
I haven't tried; I just needed the bounds updated to get Servant building on GHC 9.2

**Comment by swamp-agr** [comment]
@ysangkok there is long-standing GHC bug that should be fixed in 9.2, i.e. failing doctests such as:
```haskell
instance ToSchema Person
```
Surely, we can add that support. I was hoping that bug will gone. Let me further look into that.

**Comment by swamp-agr** [comment]
Other (unrelated to this PR) thing I want to pay attention is too relaxed `aeson` boundary which produces failing CI pipeline. Since there is nothing to do with GHC 9.2, let me fix it in separate PR.

**Comment by swamp-agr** [comment]
@ysangkok for some reason I missed it.

**Comment by swamp-agr** [comment]
@brandon-leapyear could you please rebase/merge over the Merged #230?

**Comment by brandon-leapyear** [comment]
Done

**Comment by swamp-agr** [comment]
Thanks @brandon-leapyear! I just realised that we have to ensure on CI that 9.2 is good. I will check it separately with #232.

**Comment by swamp-agr** [comment]
Before release we have to investigate and potentially fix what is going on here (from CI):

Screenshot 2022-02-03 at 18 55 54

**Comment by ysangkok** [comment]
@swamp-agr I have submitted a PR to fix that.

**Pull request merged**
