### PR TITLE
ToParamSchema class

### LINKED ISSUE #16: ToParam class
This should probably look like this:

```haskell
class ToParam a where
  toParam :: proxy a -> ParameterLocation -> ParameterOtherSchema
```

### PR DESCRIPTION
**Pull request by fizruk**
Closes #16.

This PR is incomplete.

### CODE REVIEW

**Comment by fizruk** [comment]
So here's some design problem:

We have `Param`, `Items` and `Header` all pretty similar:
- `Header` is exactly `Items` with description;
- `Items` is a restricted `Param` (without location, allowEmptyValue and without `file` type).

So we can probably factor out the common part (`Items`) and only consider that for a class (ignoring location).

**Comment by fizruk** [comment]
Okay, so I've moved `type`, `format` and `items` to `SchemaCommon`.
Now it represents the thing we should make a class for, that can be used for `Param`, `Items` and `Header`.

At this moment I realize that `Schema` also has `SchemaCommon` and that we can have something like this:

```haskell
class ToSchemaCommon a t i where
  toSchemaCommon :: proxy a -> SchemaCommon t i

-- | Generate a 'NamedSchema' for a type with 'ToSchemaCommon' instance.
-- This can be used as an implementation of `toNamedSchema` for plain types.
toNamedSchemaCommon ::
  (..., ToSchemaCommon a (SwaggerType Schema) SchemaItems)
  => proxy a -> NamedSchema
toNamedSchemaCommon _ =
  ( genericToName (Proxy :: Proxy a)
  , mempty & schemaSchemaCommon .~ toSchemaCommon (Proxy :: Proxy a) )
```

With `toNamedSchemaCommon ` it should be possible to avoid some code duplication (for non-object schemas):

```haskell
instance ToSchemaCommon Bool t i where ...

instance ToSchema Bool where toNamedSchema = toNamedSchemaCommon
```

**Comment by dmjio** [comment]
That's fine with me.

**Comment by fizruk** [comment]
I think the PR is ready for merge.

@dmjio please, take a look.

Once this one is merged I am going for resolving #13.
Then the package should finally be ready to be used in `servant-swagger`.

**Comment by dmjio** [comment]
:+1:

**Pull request merged**
