### PR TITLE
Allow mtl-2.3 & transformers-0.6

### PR DESCRIPTION
**Pull request by matobet**

### CODE REVIEW

**Comment by ysangkok** [comment]
@matobet I don't think this was done correctly, how did you test this?

I get an error during compilation:

```
 % cabal build --constraint='mtl>=2.3' --constraint='transformers>=0.6' -w ghc-9.2.3 --constraint='ghci>=9.2.3' --allow-newer=insert-ordered-containers:transformers --disable-tests
Resolving dependencies...
Build profile: -w ghc-9.2.3 -O1
In order, the following will be built (use -v for more details):
 - swagger2-2.8.2 (lib:swagger2) (first run)
[1 of 1] Compiling Main             ( /home/janus/flipstone/swagger2/dist-newstyle/build/x86_64-linux/ghc-9.2.3/swagger2-2.8.2/setup/setup.hs, /home/janus/flipstone/swagger2/dist-newstyle/build/x86_64-linux/ghc-9.2.3/swagger2-2.8.2/setup/Main.o )
Linking /home/janus/flipstone/swagger2/dist-newstyle/build/x86_64-linux/ghc-9.2.3/swagger2-2.8.2/setup/setup ...
Configuring swagger2-2.8.2...
Preprocessing library for swagger2-2.8.2..
Building library for swagger2-2.8.2..
[ 1 of 17] Compiling Data.Swagger.Declare ( src/Data/Swagger/Declare.hs, /home/janus/flipstone/swagger2/dist-newstyle/build/x86_64-linux/ghc-9.2.3/swagger2-2.8.2/build/Data/Swagger/Declare.o, /home/janus/flipstone/swagger2/dist-newstyle/build/x86_64-linux/ghc-9.2.3/swagger2-2.8.2/build/Data/Swagger/Declare.dyn_o )

src/Data/Swagger/Declare.hs:19:1: error:
    Could not load module ‘Control.Monad.List’
    It is a member of the hidden package ‘mtl-2.2.2’.
    Perhaps you need to add ‘mtl’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
19 | import Control.Monad.List (ListT)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by matobet** [comment]
@ysangkok thank you for finding this, created #236 with the fix.

**Comment by swamp-agr** [comment]
Please find release on Hackage: https://hackage.haskell.org/package/swagger2-2.8.3

**Comment by swamp-agr** [comment]
I think, it's better to add 9.2.3 to CI Matrix.

**Comment by swamp-agr** [comment]
With new LTS resolver `doctests` (via `stack test`) were also fixed. Released: https://hackage.haskell.org/package/swagger2-2.8.4

**Pull request merged**
