### PR TITLE
Add ParamSchema & Schema for Numeric.Natural

### PR DESCRIPTION
**Pull request by pngwjpgh**
Seems reasonable to have a Schema for Numeric.Natural; it's in base and has aeson-support.

### CODE REVIEW

**Comment by phadej** [comment]
you need to add
```
  if !impl(ghc >= 7.10)
    build-depends:
      nats               >=1.1.1    && <1.2
```

to make GHC-7.8.4 happy.

**Comment by pngwjpgh** [comment]
Okay, I don't have a testing environment for anything but the current ghc version set up, so let's just see if travis is happy :-)

**Comment by fizruk** [comment]
@pngwjpgh thanks for your contributions!

@phadej feel free to merge this and #121 when you're happy with dependency constraints.
I can make a release shortly after.

**Comment by phadej** [comment]
FWIW, I'd really like to have both upper and lower bounds. It's unluckily `nats` will get major updated, but if it will, it most likely be broken in a bad way.

**Comment by pngwjpgh** [comment]
Would you be okay with `>=0.1 && <2` then?

Version `0.1` is the first one and introduces `Numeric.Natural.Natural`.
By [semantic versioning](http://semver.org) dropping the name `Numeric.Natural.Natural` for the type would lead to a version `2.*` being an incompatible api change.

Afaik @ekmett has always been good with adhering to semantic versioning.

**Comment by phadej** [comment]
I insist on `>=1.1.1 && <1.2`. There is no need to support older versions. If we haven't ever tested with `0.1`, then we shouldn't claim we support it. Travis says on GHC-7.8.4 job

```
Loading package nats-1.1.1 ... linking ... done.
```

Hackage uses [PVP](https://pvp.haskell.org/) where two first digits act as major, third as a minor and fourth as a patch. So  in this case `nats-1.2` might introduce breaking change (unluckily, but still).

**Comment by phadej** [comment]
also rebase needed now.

**Comment by pngwjpgh** [comment]
Valid points. Thanks for linking me to PVP, I didn't know about that :-D

**Comment by ekmett** [comment]
Just for the record, I follow the PvP as closely as I can. In addition I reserve the first digit for major overhauls that break my own packages. (This can make my package bounds look a bit like sem-ver.) Restricting off the second digit as @phadej notes is the correct option per the PVP.

**Pull request merged**
