### PR TITLE
Moved types used by tests to CommonTestTypes, unifing them

### PR DESCRIPTION
**Pull request by przemoli**
#129 
I moved types from test/Data/Swagger/{ParamSchemaSepc|SchemaSpec} to single module, and for duplicates I just copied extra Deriving and instances.

### CODE REVIEW

**Comment by fizruk** [comment]
The problem with GHC 7.8 is that you have to import `Control.Applicative` to get `pure` and `<$>`.
Something like this should work:

```haskell
#if __GLASGOW_HASKELL__ <710
import Control.Applicative
#endif
```

**Comment by fizruk** [comment]
Also, apparently you have all the code indented by 2 whitespaces, that's probably unintended?

Apart from those comments seems good, thanks for your contribution!

**Comment by phadej** [comment]
```haskell
-#if __GLASGOW_HASKELL__ <710
-import Control.Applicative
-#endif
+import Prelude ()
+import Prelude.Compat
```

**Comment by przemoli** [comment]
I've updated imports to use Prelude.Compat, and I've rebased my commits on top of recent PR.

**Pull request merged**
