### PR TITLE
Use Aeson `>=2.0.0.0  && <2.1` and GitHub Actions

### LINKED ISSUE #226: Aeson security Issue (Servant dependency)
Hi swagger2 maintainers,

I am a [servant](https://github.com/haskell-servant/servant) maintainer and I am trying to bump aeson following the [security issue](https://github.com/haskell/aeson/issues/864) 
Servant has a dependency with **swagger2** but [aeson](https://github.com/GetShopTV/swagger2/blob/51f2108826dff2a0c31b581025e8f9f9b29accb1/swagger2.cabal#L76) has been bounded below 1.6

Would it be possible to relax constraint for **aeson** (>= 2.0.0.0)?

### PR DESCRIPTION
**Pull request by alissa-tung**
close #226 , re #227 
cc @swamp-agr @akhesaCaro
also close #223 , #225 , #214

### CODE REVIEW

**Comment by alissa-tung** [comment]
Hello @fizruk , could you please help me enable the continuous-integration check

**Comment by alissa-tung** [comment]
Seems okay except a macOS issue, I gonna inspect this.
https://github.com/alissa-tung/swagger2/actions/runs/1438001851

**Review by swamp-agr — APPROVED** [review]
@alissa-tung thank you for your contribution!

✅  PR looks good to me.
CI might be enabled and processed separately. 
I will check and prepare release today later.

**Comment by swamp-agr** [comment]
> Seems okay except a macOS (stack) issue, I gonna inspect this.

According to the log `doctests` failed.

**Comment by swamp-agr** [comment]
As far as I understand:

- Segfault appeared for `stack (LTS-18.16) + GHC 8.10.7 + doctests` as well as for `cabal + GHC 9.0.1`: https://gitlab.haskell.org/ghc/ghc/-/issues/19460. 
- To be more specific, following line will cause an error during doctests execution:
    ```
    instance ToSchema Person
    ```
- It seems that doctests should be fixed in GHC 9.2.1. 

@alissa-tung if you confirm that
- ignoring such an error would work for you
- GHC 8.8.4 would work fine 

then we'll go release the package keeping in mind to add 9.2.1 support as soon as possible and either skipping `9.0.x` and `8.10.x` or explicitly mentioning mysterious behaviour of compiler and tooling.

**Comment by alissa-tung** [comment]
> CI might be enabled and processed separately. I will check and prepare release today later.

I am not sure the stagey for GitHub to take when removing the Travis CI file and add Actions `.github/workflows/ci.yml`. Which one would be better to make further development (Travis CI, GitHub Actions or both)? If we are going to enable actions the README.md should be updated later.

`stack (LTS-18.16) + GHC 8.10.7 + doctests` works fine on my machine.
But tested Cabal with 9.0.1 failed.
In fact I am curious about why Ubuntu + stack.yaml works fine but macOS failed with the same result. :thinking: 
Thank you for shed light on the specific line! I had never thought about this way before :+1:  I thinking the way of discovering must be mysterious.
We can keep in touch with the test result with Cabal by adding more GHC version constraints in the GitHub Actions `matrix`. For stack maybe we should add more stack files.

----------------------------------------------------------------

> GHC 8.8.4 would work fine?

If it is not caused by the changes I had made :thinking: Another project I am working on uses 8.8.4 with `swagger2` everyday and no issue like this had been noticed before. or it merely affects the GHCi? im not sure. Let's add it into CI and see.

**Comment by alissa-tung** [comment]
The status of CI for 8.8.4 can be found [here](https://github.com/alissa-tung/swagger2/actions/runs/1439457857).

**Comment by swamp-agr** [comment]
Personally I want to get rid of Travis CI since after it changed its host (from travis-ci.org to travis-ci.com) we have a plenty of jobs stalled here. And I have no control on it. I cannot bypass restrictions set on this repository. Github Actions seems a good choice, thank you for advising and setting it up.

@fizruk could you please go ahead and shut down Travis CI integration permanently? Unfortunately, I cannot do it by myself.

Screenshot 2021-11-09 at 15 23 18

**Comment by alissa-tung** [comment]
cc @swamp-agr seems that the blocking status is canceled. looking forward to your review opinions

**Comment by swamp-agr** [comment]
@alissa-tung please find package released on Hackage: https://hackage.haskell.org/package/swagger2-2.7.

**Pull request merged**
